site_name: pyhwpx
site_url: https://martiniifun.github.io/pyhwpx
repo_url: https://github.com/martiniifun/pyhwpx
repo_name: martiniifun/pyhwpx
theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  custom_dir: overrides
  language: ko
  features:
    - header.autohide
    - navigation.top
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
#  - mike:
#      alias_type: symlink
#      redirect_template: null
#      deploy_prefix: ''
#      canonical_version: null
#      version_selector: true
#      css_dir: css
#      javascript_dir: js
  - offline
  - git-authors
  - git-committers:
      repository: martiniifun/pyhwpx
      branch: master
      token: !!python/object/apply:os.getenv["MKDOCS_GIT_COMMITTERS_APIKEY"]
      enabled: !ENV [CI, false]
#  - git-revision-date-localized:
#      enable_creation_date: true
#      fallback_to_build_date: true
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

nav:
  - Home: index.md
  - API: api.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@docsearch/js@3

extra_css:
  - https://cdn.jsdelivr.net/npm/@docsearch/css@3

extra:
#  social:
#    - icon: fontawesome/brands/
#  version:
#    provider: mike
  docsearch:
    app_id: U3N1V3HJZN
    api_key: 7cab876aeab826c0e4c392da7cdd2e29
    index_name: martiniifunio
    insights: true
    debug: false
  analytics:
    provider: google
    property: G-J3X00QMZKL
    feedback:
      title: 이 페이지의 정보가 도움이 되었나요?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 도움이 되었습니다.
          data: 1
          note: >-
            피드백을 남겨주셔서 감사합니다!
            그래도 pyhwpx모듈이나 웹문서에 개선할 부분이 있다면 어떤 점이 좋을지 남겨주시겠어요? 질문이나 건의사항도 좋습니다.
            자유롭게 메시지 남겨주세요. 행복한 하루 되세요!!^^
            <a href="https://forms.gle/XLYfrvx4WCLZXDXb8" target="_blank" rel="noopener">메시지 남기기</a>
        - icon: material/emoticon-sad-outline
          name: 페이지가 조금 더 개선이 되어야 합니다.
          data: 0
          note: >-
            피드백을 주셔서 감사합니다!
            어떤 부분, 또는 어떤 설명이 추가되면 좋을지 익명으로(실명이나 별명도 좋아요!) 자유롭게 남겨주세요!
            겸허히 받아들이고 적극 반영하겠습니다!!!! 행복한 하루 되세요!!^^
            <a href="https://forms.gle/XLYfrvx4WCLZXDXb8" target="_blank" rel="noopener">메시지 남기기</a>