site_name: pyhwpx
site_url: https://martiniifun.github.io/pyhwpx
repo_url: https://github.com/martiniifun/pyhwpx
theme:
  name: material
  language: ko
  features:
    - navigation.top
    - navigation.indexes
    - navigation.prune
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.highlight
    - search.suggest
    - search.share
    - toc.follow
    - toc.integrate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true

nav:
  - Home: index.md
  - API: api.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/@docsearch/js@3

extra_css:
  - https://cdn.jsdelivr.net/npm/@docsearch/css@3

extra:
  docsearch:
    app_id: U3N1V3HJZN
    api_key: 7cab876aeab826c0e4c392da7cdd2e29
    index_name: martiniifunio
    insights: true
    debug: false
  analytics:
    provider: google
    property: G-J3X00QMZKL
    feedback:
      title: 이 페이지의 정보가 도움이 되었나요?
      ratings:
        - icon: material/emoticon-happy-outline
          name: 도움이 되었습니다.
          data: 1
          note: >-
            피드백을 주셔서 감사합니다!
        - icon: material/emoticon-sad-outline
          name: 페이지가 조금 더 개선이 되어야 합니다.
          data: 0
          note: >-
            피드백을 주셔서 감사합니다!
            어떤 부분, 또는 어떤 설명이 추가되면 좋을지 익명으로 남겨주세요!
            <a href="..." target="_blank" rel="noopener">피드백 보내기</a>